# Generated by Django 4.2.11 on 2024-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Altmetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('doi', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('mendeley_readers', models.IntegerField()),
                ('score', models.IntegerField()),
                ('facebook', models.IntegerField()),
                ('x', models.IntegerField()),
                ('blogs', models.IntegerField()),
                ('news', models.IntegerField()),
                ('reddit', models.IntegerField()),
                ('stackoverflow', models.IntegerField()),
                ('policies', models.IntegerField()),
                ('patents', models.IntegerField()),
                ('youtube', models.IntegerField()),
                ('wikipedia', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
