# Generated by Django 4.2.11 on 2024-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetrics',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
