# Generated by Django 4.2.11 on 2024-04-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_altmetrics_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetrics',
            name='doi',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
