# Generated by Django 4.2.11 on 2024-04-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_altmetrics_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetrics',
            name='year',
            field=models.IntegerField(),
        ),
    ]
