# Generated by Django 4.2.11 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_altmetrics_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetrics',
            name='doi',
            field=models.CharField(max_length=100),
        ),
    ]
