# Generated by Django 4.2.11 on 2024-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_altmetrics_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestasForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField()),
                ('genero', models.CharField(max_length=10)),
                ('jeraquia', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('r4', models.IntegerField()),
                ('r5', models.IntegerField()),
                ('r6', models.IntegerField()),
                ('r7', models.IntegerField()),
                ('r8', models.IntegerField()),
                ('r9', models.IntegerField()),
                ('r10', models.IntegerField()),
                ('r11', models.IntegerField()),
                ('r12', models.IntegerField()),
                ('r13', models.IntegerField()),
                ('r14', models.IntegerField()),
                ('r15', models.IntegerField()),
            ],
        ),
    ]
