# Generated by Django 4.2.11 on 2024-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_respuestasform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestasform',
            old_name='jeraquia',
            new_name='jerarquia',
        ),
    ]
